services:
  - type: web
    name: andromeda
    env: node
    buildCommand: npm install -g pnpm && pnpm install && pnpm run build
    startCommand: pnpm start
    envVars:
      - key: PORT
        value: 5000
      - key: INFURA_API_KEY
        sync: false
      - key: SPENDER_PRIVATE_KEY
        sync: false
      - key: SPENDER_ADDRESS
        sync: false
      - key: NODE_ENV
        value: production 